### ISSUE TITLE
working on 2.2.chat - session ( one user per browser )

### ISSUE THREAD

**Issue by yussan** [yussan/exploration-socket.io#1]
for now chat is working, but there are on disadvantages, I show the following in the checklist :
- [x] save username in session
- [x] so everytime user open web, check session first, if username available auto login.
- [x] save session in cookie

project dir https://github.com/yussan/exploration-socket.io/tree/master/2.2.chat%20-%20session%20(%20one%20user%20per%20browser%20)

**Comment by x4th** [comment]
Hi, I'd like to tackle this. Is it alright if I use the js-cookie package in order to simplify cookie operations?

**Comment by yussan** [comment]
thanks, go ahead
